### ISSUE TITLE
Revisit Jitters with Dirichlet or extra variance

### ISSUE THREAD

**Issue by shcaba** [shcaba/SS-DL-tool#28]
Dirichlet estimates parameters for the data weighting. In jitters, maybe this and extra variance should not be estimated? Need to think this through.

**Comment by iantaylor-NOAA** [comment]
I think that if there's enough information to estimate these quantities in the base model, then it's useful to find out if jittering their starting values causes them to end up in a different place (and thus change likelihood). Otherwise, the jittering might be too easy a test to pass.

**Comment by shcaba** [comment]
Problem is the likelihoods are no longer comparable. Unless I am missing something, a lower likelihood value from a different data-weighting will no longer mean a relatively better fit than the reference model.

**Comment by iantaylor-NOAA** [comment]
My understanding is that the likelihood incorporates Dirichlet-multinomial parameters, extra survey variances, and variance parameters like sigmaR in a way that makes the likelihood comparable across models with different values. If that were NOT the case, we could never estimate those parameters because a better likelihood would not necessarily correspond to a better fit. That's the beauty of the D-M likelihood compared to iterative tuning algorithms. Note that we never see giant estimates of the extra survey variance which would make it look like the survey data fit really well because the sigma occurs elsewhere in the likelihood. We might need a true random effects model to get unbiased estimates of some of those parameters, but I believe the likelihoods are still comparable even without that.

@James-Thorson-NOAA can surely explain this better, or maybe he'll just tell us to go read [Let’s simplify stock assessment by replacing tuning algorithms with statistics](https://doi.org/10.1016/j.fishres.2018.02.005).

**Comment by James-Thorson-NOAA** [comment]
I agree that with D-M and lognormal additive variance (or additive SD, whichever SS3 is using right now), the likelihood *is* comparable across different values, and therefore it might make sense to jitter within appropriate bounds etc.  I'm of course excited to catch up about how y'all are using these tools after next cycle

**Comment by shcaba** [comment]
If set up that way, then it sounds like there is no issue with this. Thank you both for the discussion!
