### ISSUE TITLE
Growth is accidentally fixed for males when attempting to estimate a combined growth curve

### ISSUE THREAD

**Issue by jonathansmart** [shcaba/SS-DL-tool#91]
It appears when estimating combined growth for females and males the .ctl file is not setup correctly. For male growth to match female growth the INIT value should be zero and the phase should be negative. However, when setting up growth estimation in SS-DL with no male specific values, the male growth curve becomes fixed at the INIT value used for females. 

Please close this issue if I have mis-diagnosed the problem.

**Comment by shcaba** [comment]
Hi Jonathan-- Thanks for highlighting this topic.

When you are in the life history estimation mode, there should be text right above the male section that says:

**Enter male specific values. Otherwise, males are assumed equal to females**
**_If estimating females and wanting to match males to estimated female parameters, use the male offset option and set offsets to 0. This will ensure male values are equal to estimated female males. Otherwise, males will retain the initial female values._**

That second direction notes that in order to avoid estimating females, but fixing males to the initial female values, you need to use the offset approach (checkbox on the right side). That allows males to relate to females via a log offset of ln(male_value/female_value). This is specifically for the natural mortality and the 5 growth parameters (weight-length parameters are always pre-specified, thus in normal space). So if you wanted to estimate male values different from femalee, but wanted to start at the female initial values, all mean values for the males would be set to 0 (thus exp(0) is male/female = 1). From there, you can then turn the phase on for whatever parameters you want to estimate different from females. If you want the initial male values different from females, then use the ln(male_value/female_value). 

**As an example for natural mortality, if female was 0.1 and males 0.12, for the male offset value, you would use ln(0.12/0.1) = 0.1823216.**

I hope this explains how to have the flexibility to have males the same or different from females under a variety of pre-specified or estimated situations.

**Comment by jonathansmart** [comment]
Thanks for the thorough explanation Jason. I checked 'Males offset from females' box and nothing further happens with the GUI. Do I then enter the these offset values into the existing fields? This might have been what threw me as I was expecting more options to occur. Thanks.

**Comment by shcaba** [comment]
That is correct- those value just go in the same pulldown menus as before.
So where it says mean, you would put in the mean offset value. I would
recommend trying 0 for all (thus setting male starting values the same as
females) just to see what happens.

The parameter section in the Report file will also show the male values as
offsets of females. But if you go way down to the  Biology section where
growth parameters are reported, those offsets are transformed back into the
normal values.
I hope this is helpful!


*Jason M. Cope, Ph.D.Research Fishery Biologist*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2725 Montlake Blvd. East*

*Seattle, WA 98112-2013*
*NOAA Fisheries*
*Affiliate assistant faculty*
*School of Aquatic and Fishery Sciences*
*University of Washington*
***@***.*** ***@***.***>
(206) 302-2417
www.nmfs.noaa.gov
